services:
  flask:
    volumes:
      - ./app:/app/app
      - ./run.py:/app/run.py
    build:
      dockerfile: dev.Dockerfile
    command: python run.py
    ports:
      - 5000:5000
    restart: unless-stopped
    